name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:       
      - name: SSH into VM with password
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_PUBLIC_IP }} << EOF
            ls
            # Set GitHub credentials using GITHUB_TOKEN
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" > ~/.git-credentials
          # Pull the latest code from the repository
          cd deploy/
          rm -rf recruitment-ai
          git clone -b develop https://github.com/sagar686/recruitment-ai
          cd recruitment-ai/
          docker compose build
          docker compose up

