name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log GitHub Actions Secrets
        env:
          SECRET_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}          
        run: |
          echo "Username: $SECRET_AZURE_CREDENTIALS"   
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Run a one-line script
        run: echo Hello, world!
