name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log GitHub Actions Secrets
        env:
          SECRET_AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS}}   
          SECRET_OPENAI: ${{ secrets.OPENAI_API_KEY}}          

        run: |
          echo "AZ $SECRET_AZURE_CREDENTIALS"
          echo "OPEN AI $SECRET_OPENAI" 

          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
        
      - name: SSH into VM with password
        run: |
          az ssh vm \
            --ip ${{ secrets.VM_PUBLIC_IP }} \
            --local-user ${{ secrets.VM_USERNAME }} \
            --auth-type password \
            --password ${{ secrets.VM_PASSWORD }}
            
      - name: Run a one-line script
        run: echo Hello, world!
